### ISSUE TITLE
align the nav bar -reduce the logo size n font size

### ISSUE THREAD

**Issue by zephyr007** [zephyr007/crextal18.tech#12]
![5](https://user-images.githubusercontent.com/32525557/38103792-f86a6246-33a4-11e8-88ed-062d1f6099f5.png)

**Comment by zephyr007** [comment]
Use photoshop 
to reduce size

**Comment by dhruv10** [comment]
@shivamkansal  has some issue's with his Github account.

**Comment by dhruv10** [comment]
+ Remove extra tabs

**Comment by zephyr007** [comment]
Its done
